import React, { useState } from "react";
import { Icon } from "./Icons";

const EXAMPLES = [
  { key: "invoice", label: "Invoice", detail: "Logos, line items, totals. All editable.", format: "A4 · PDF", binding: "data.invoice.customer.name" },
  { key: "receipt-58mm", label: "Receipt", detail: "A little paper. A whole basket of possibilities.", format: "58 mm · ESC/POS", binding: "row.description" },
  { key: "label-50x30", label: "Label", detail: "Small formats. Precisely placed details.", format: "50 × 30 mm · ZPL", binding: "row.name" },
] as const;

export function ReportShowcase({ onExample }: { onExample: (key: string) => void }) {
  const [selected, setSelected] = useState(0);
  const example = EXAMPLES[selected]!;
  return <div className="report-showcase">
    <div className="showcase-toolbar"><span><i /> THE POSSIBILITIES, ON PAPER</span><Icon name="grid" /></div>
    <div className={`showcase-stage showcase-stage-${example.key}`}>
      <div className="showcase-orbit" aria-hidden="true"><span /><span /></div>
      <div className="showcase-ruler" aria-hidden="true"><span>0</span><span>50</span><span>100</span><span>150</span><span>200</span></div>
      <div className="showcase-paper-back" aria-hidden="true" />
      <div className="showcase-paper" key={example.key}>
        <img src={`/landing/reports/${example.key}.webp`} alt={`Actual ${example.label.toLowerCase()} output generated by Open Reports`} width="680" height="960" loading="eager" />
        <div className="showcase-selection" aria-hidden="true"><span /><span /><span /><span /></div>
      </div>
      <div className="showcase-data"><span className="showcase-data-icon">{ "{ }" }</span><div><span>YOUR DATA, CONNECTED</span><code>{example.binding}</code></div><Icon name="check" /></div>
      <div className="showcase-format"><Icon name="file" /><span>{example.format}</span></div>
      <div className="showcase-cursor" aria-hidden="true"><svg width="25" height="31" viewBox="0 0 25 31"><path d="m2 2 19 16-10 1-4 9Z" fill="currentColor" stroke="var(--paper)" strokeWidth="2" /></svg><span>Make it yours</span></div>
    </div>
    <div className="showcase-bottom">
      <div className="showcase-switcher" role="group" aria-label="Report preview">
        {EXAMPLES.map((item, index) => <button key={item.key} type="button" aria-pressed={selected === index} onClick={() => setSelected(index)}>{item.label}</button>)}
      </div>
      <button className="showcase-open" data-testid="showcase-open" onClick={() => onExample(example.key)} aria-label={`Open ${example.label.toLowerCase()} example in the designer`}><Icon name="arrow" /></button>
    </div>
    <p className="showcase-caption" aria-live="polite">{example.detail}</p>
  </div>;
}
